  		<nav>
        <ul class="social">
          <li><a href="https://www.facebook.com/pages/Chicago-Line-Cruises/201612763202175"><img width="11" height="20" alt="Facebook" src="/assets/images/social/facebook.png"></a></li>
          <li><a href="https://twitter.com/chicagoline"><img width="22" height="18" alt="Twitter" src="/assets/images/social/twitter.png"></a></li>
          <li><a href="https://instagram.com/chicagolinecruises/"><img width="21" height="19" alt="Instagram" src="/assets/images/social/instagram.png"></a></li>
          <li><a href="https://www.pinterest.com/chicagoline/chicago-line-cruises/"><img width="15" height="19" alt="Pinterest" src="/assets/images/social/pinterest.png"></a></li>
          <li><a href="https://www.youtube.com/user/ChicagolineCruises/videos"><img width="22" height="22" alt="YouTube" src="/assets/images/social/youtube.png"></a></li>
          <li><a href="http://www.tripadvisor.com/Attraction_Review-g35805-d667926-Reviews-Chicago_Line_Cruises-Chicago_Illinois.html"><img width="28" height="17" alt="Trip Advisor" src="/assets/images/social/tripadvisor.png"></a></li>
          <li><a href="http://www.yelp.com/biz/chicago-line-cruises-chicago-2"><img width="18" height="22" alt="Yelp" src="/assets/images/social/yelp.png"></a></li>
          <li><a href=""><img src="/assets/images/social/blog.png"></a></li>
          <li><a href="mailto:contactus@chicagoline.com"><img width="28" height="18" alt="Email" src="/assets/images/social/email.png"></a></li>
        </ul>
  		</nav>
