  		<aside id="footer-text" class="clearfix">
        <p>Our boats and ticket office are located just north of the Centennial Fountain at 465 McClurg Court.  Call us at 312-527-1977.</p>
        <p><span class="copyright">&copy; Chicago From The Lake, Ltd.</span> Photography by R. L. Segal</p>
  		</aside>
  		
  		<aside id="footer-text-m" class="clearfix">
        <p>Our boats and ticket office are located just north of the Centennial Fountain at 465 McClurg Ct.</p>
  		</aside>
