        <ul class="nav">
          <li><a href="/schedules.php"><img alt="Cruise Schedule" width="47" height="57" src="/assets/images/icons/color-schedule.png"></a></li>
          <li><a href="https://goo.gl/maps/4UVkK" target="_blank"><img alt="Cruise Location" width="47" height="57" src="/assets/images/icons/color-location.png"></a></li>
          <li><a href="<?php echo PURCHASE_URL; ?>"><img alt="Purchase Tickets" width="47" height="57" src="/assets/images/icons/color-purchase.png"></a></li>
        </ul>

