		<ul class="mobile-icons clearfix">
			<li><a href="<?php echo PURCHASE_URL; ?>" onClick="ga('send', 'event', { eventCategory: 'Purchase Ticket', eventAction: 'Start Checkout', eventLabel: 'clicked'});"><img alt="Purchase Tickets" src="/assets/images/icons/mobile-purchase.png"></a></li>
			<li><a href="https://goo.gl/maps/4UVkK" target="_blank"><img alt="Cruise Location" src="/assets/images/icons/mobile-location.png"></a></li>
			<li><a href="/contact.php"><img alt="Contact" src="/assets/images/icons/mobile-phone.png"></a></li>
		</ul>